# Build stage
FROM node:21.7.3-alpine AS build

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

RUN npm run build

# Production stage
FROM node:21.7.3-alpine AS production

WORKDIR /app

COPY package*.json .

COPY next.config.mjs .

COPY tailwind.config.ts .

RUN npm ci --only=production

COPY --from=build /app/.next ./.next

EXPOSE 3000

ENV PORT 3000

ENV NEXT_PUBLIC_API_URL=http://localhost:3020

CMD ["npm", "run", "start"]